providers = ["node", "python"]

[variables]
PORT = "8000"

[phases.setup]
nixPkgs = ["nodejs_18", "python311"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm --prefix frontend install"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build"
]

[phases.start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
