providers = ["python"]

[variables]
PORT = "8000"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "curl -fsSL https://deb.nodesource.com/setup_18.x | bash -",
  "apt-get install -y nodejs",
  "npm --prefix frontend install"
]

[phases.build]
cmds = [
  "npm --prefix frontend run build"
]

startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
